version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  frontend-prod:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    command: serve -s dist




# development
# docker-compose up frontend-dev --build

# production
# docker-compose up frontend-prod --build